# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadPatternDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadPatternDialog(object):
    def setupUi(self, LoadPatternDialog):
        LoadPatternDialog.setObjectName("LoadPatternDialog")
        LoadPatternDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadPatternDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.patternsListWidget = QtWidgets.QListWidget(LoadPatternDialog)
        self.patternsListWidget.setObjectName("patternsListWidget")
        self.verticalLayout.addWidget(self.patternsListWidget)
        self.loadButton = QtWidgets.QPushButton(LoadPatternDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)

        self.retranslateUi(LoadPatternDialog)
        QtCore.QMetaObject.connectSlotsByName(LoadPatternDialog)

    def retranslateUi(self, LoadPatternDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadPatternDialog.setWindowTitle(_translate("LoadPatternDialog", "Dialog"))
        self.loadButton.setText(_translate("LoadPatternDialog", "Load Pattern"))
